// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['bindings']['ClientBindings']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['bindings']['ClientBindings']['Delete'](arg1);
}

export function GetAll() {
  return window['go']['bindings']['ClientBindings']['GetAll']();
}

export function GetByID(arg1) {
  return window['go']['bindings']['ClientBindings']['GetByID'](arg1);
}

export function Search(arg1) {
  return window['go']['bindings']['ClientBindings']['Search'](arg1);
}

export function Update(arg1) {
  return window['go']['bindings']['ClientBindings']['Update'](arg1);
}
