// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function Create(arg1:models.ClientDocument):Promise<void>;

export function Delete(arg1:number):Promise<void>;

export function DownloadDocument(arg1:number):Promise<void>;

export function GenerateAndSave(arg1:number):Promise<string>;

export function GetAll():Promise<Array<models.ClientDocument>>;

export function GetByClientID(arg1:number):Promise<Array<models.ClientDocument>>;

export function GetByID(arg1:number):Promise<models.ClientDocument>;

export function Save(arg1:models.ClientDocument):Promise<void>;

export function Search(arg1:models.ClientDocumentSearch):Promise<Array<models.ClientDocument>>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Update(arg1:models.ClientDocument):Promise<void>;
