// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['bindings']['ClientDocumentBindings']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['bindings']['ClientDocumentBindings']['Delete'](arg1);
}

export function GetAll() {
  return window['go']['bindings']['ClientDocumentBindings']['GetAll']();
}

export function GetByID(arg1) {
  return window['go']['bindings']['ClientDocumentBindings']['GetByID'](arg1);
}

export function Update(arg1) {
  return window['go']['bindings']['ClientDocumentBindings']['Update'](arg1);
}
