// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoScan(arg1) {
  return window['go']['bindings']['DocumentTemplateBindings']['AutoScan'](arg1);
}

export function Create(arg1) {
  return window['go']['bindings']['DocumentTemplateBindings']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['bindings']['DocumentTemplateBindings']['Delete'](arg1);
}

export function GetAll() {
  return window['go']['bindings']['DocumentTemplateBindings']['GetAll']();
}

export function GetByID(arg1) {
  return window['go']['bindings']['DocumentTemplateBindings']['GetByID'](arg1);
}

export function PickAndScanTemplate() {
  return window['go']['bindings']['DocumentTemplateBindings']['PickAndScanTemplate']();
}

export function SetContext(arg1) {
  return window['go']['bindings']['DocumentTemplateBindings']['SetContext'](arg1);
}

export function Update(arg1) {
  return window['go']['bindings']['DocumentTemplateBindings']['Update'](arg1);
}
