// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function AutoScan(arg1:string):Promise<Array<string>>;

export function Create(arg1:models.DocumentTemplate):Promise<void>;

export function Delete(arg1:number):Promise<void>;

export function GetAll():Promise<Array<models.DocumentTemplate>>;

export function GetByID(arg1:number):Promise<models.DocumentTemplate>;

export function PickAndScanTemplate():Promise<models.ScanResult>;

export function Search(arg1:models.DocumentTemplateSearch):Promise<Array<models.DocumentTemplate>>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Update(arg1:models.DocumentTemplate):Promise<void>;
