// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function Create(arg1:models.EmployeeDocument):Promise<void>;

export function Delete(arg1:number):Promise<void>;

export function DownloadDocument(arg1:number):Promise<void>;

export function GenerateAndSave(arg1:number):Promise<string>;

export function GetAll():Promise<Array<models.EmployeeDocument>>;

export function GetByEmployeeID(arg1:number):Promise<Array<models.EmployeeDocument>>;

export function GetByID(arg1:number):Promise<models.EmployeeDocument>;

export function Save(arg1:models.EmployeeDocument):Promise<void>;

export function Search(arg1:models.EmployeeDocumentSearch):Promise<Array<models.EmployeeDocument>>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Update(arg1:models.EmployeeDocument):Promise<void>;
