// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['bindings']['EmployeeBindings']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['bindings']['EmployeeBindings']['Delete'](arg1);
}

export function GetAll() {
  return window['go']['bindings']['EmployeeBindings']['GetAll']();
}

export function GetByID(arg1) {
  return window['go']['bindings']['EmployeeBindings']['GetByID'](arg1);
}

export function Update(arg1) {
  return window['go']['bindings']['EmployeeBindings']['Update'](arg1);
}
