// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Create(arg1:models.Employee):Promise<void>;

export function Delete(arg1:number):Promise<void>;

export function GetAll():Promise<Array<models.Employee>>;

export function GetByID(arg1:number):Promise<models.Employee>;

export function Update(arg1:models.Employee):Promise<void>;
