// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['bindings']['NoteBindings']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['bindings']['NoteBindings']['Delete'](arg1);
}

export function GetAll() {
  return window['go']['bindings']['NoteBindings']['GetAll']();
}

export function GetByID(arg1) {
  return window['go']['bindings']['NoteBindings']['GetByID'](arg1);
}

export function Search(arg1) {
  return window['go']['bindings']['NoteBindings']['Search'](arg1);
}

export function Update(arg1) {
  return window['go']['bindings']['NoteBindings']['Update'](arg1);
}
