// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Create(arg1:models.Note):Promise<void>;

export function Delete(arg1:models.Note,arg2:number):Promise<void>;

export function GetAll():Promise<Array<models.Note>>;

export function GetByID(arg1:number):Promise<models.Note>;

export function Search(arg1:string):Promise<Array<models.Note>>;

export function Update(arg1:models.Note):Promise<void>;
