// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Create(arg1:models.Task):Promise<void>;

export function Delete(arg1:number):Promise<void>;

export function GetAll():Promise<Array<models.Task>>;

export function GetByID(arg1:number):Promise<models.Task>;

export function Search(arg1:models.TaskSearch):Promise<Array<models.Task>>;

export function Update(arg1:models.Task):Promise<void>;
