// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Create(arg1:models.Transaction):Promise<void>;

export function Delete(arg1:number):Promise<void>;

export function GetAll():Promise<Array<models.Transaction>>;

export function GetByID(arg1:number):Promise<models.Transaction>;

export function Search(arg1:models.TransactionSearch):Promise<Array<models.Transaction>>;

export function Update(arg1:models.Transaction):Promise<void>;
