// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['bindings']['TransactionBindings']['Create'](arg1);
}

export function Delete(arg1, arg2) {
  return window['go']['bindings']['TransactionBindings']['Delete'](arg1, arg2);
}

export function GetAll() {
  return window['go']['bindings']['TransactionBindings']['GetAll']();
}

export function GetByID(arg1) {
  return window['go']['bindings']['TransactionBindings']['GetByID'](arg1);
}

export function Update(arg1) {
  return window['go']['bindings']['TransactionBindings']['Update'](arg1);
}
